### ISSUE TITLE
Release import

### ISSUE THREAD

**Issue by szepeviktor** [zpaq/zpaq-tools#1]
@nemequ Could you add the release import script here?
https://github.com/zpaq/zpaq/releases

**Comment by nemequ** [comment]
Hm, it's just something I threw together in a couple minutes a few years ago…  I never really intended to publish it, so it's a bit ugly and specific to my system.

Also, all the script does is generate the tags, it will not upload the original zips to github.  I did that manually (only takes a second if the tag has already been uploaded).

I wouldn't feel comfortable importing it into the repo until I clean it up a bit, but FWIW here is what it looks like right now:

``` sh
#!/bin/sh

echo -e "Web site: http://mattmahoney.net/dc/zpaq.html\n\n"

cd ~/local/src/zpaq
echo "Enter version (e.g., 6.48)"
read VERSION
echo "Enter commit message"
read COMMIT_MSG

ZIP=zpaq$(echo $VERSION | sed 's/\.//').zip

git rm -rf *

wget "http://mattmahoney.net/dc/${ZIP}" || exit
DATE=$(date -u --iso-8601=seconds --date="$(stat -c %y ${ZIP})")

export GIT_COMMITTER_NAME="Matt Mahoney"
export GIT_COMMITTER_EMAIL="mattmahoneyfl@gmail.com"
export GIT_COMMITTER_DATE="${DATE}"

export GIT_AUTHOR_NAME="${GIT_COMMITTER_NAME}"
export GIT_AUTHOR_EMAIL="${GIT_COMMITTER_EMAIL}"
export GIT_AUTHOR_DATE="${GIT_COMMITTER_DATE}"

unzip -o "${ZIP}" && \
    rm -f *.{zip,exe,pdf} && \
    dos2unix *.{h,cpp} readme.txt Makefile && \
    git add * && \
    git commit -m "${COMMIT_MSG}" && \
    git tag "${VERSION}"
```

**Comment by szepeviktor** [comment]
Thanks.

**Comment by szepeviktor** [comment]
ps. My fantasy was to parse Matt's website and use GitHub API.

**Comment by nemequ** [comment]
> ps. My fantasy was to parse Matt's website and use GitHub API.

That's probably possible, but it's more work than I'm willing to put in.  Patches welcome, though ;)
